# Generated by Django 4.2.23 on 2025-06-17 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_dailyoffer'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='product',
            new_name='products_pr_id_a08e3c_idx',
            old_fields=('id', 'slug'),
        ),
    ]
